spring:
  main:
   allow-circular-references: true
  mvc:
   pathmatch:
    matching-strategy: ant-path-matcher
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:moviesbattle
    username: sa
    password: 1234
    driverClassName: org.h2.Driver

omdb-api:
  url: http://omdbapi.com/
  key: 42c7d292

server:
  servlet:
    context-path: /ada

    


